/* CARDS — sourced from the Anime Card Clash Fandom wiki (All Cards page).
   Images are the real static.wikia.nocookie.net URLs pulled straight from
   the wiki's file records, not guessed — Fandom's image paths are a content
   hash and can't be constructed from the card name alone.

   Fields:
     id          slug, used for anchors
     name        card name as listed on the wiki
     altName     the source character the card is based on, if the wiki lists one
     role        "Attacker" | "Support"
     pool        where it's pulled from — "Standard Pool", "Snow Moon", etc.
     tier        rank from the community Meta Attacker / Support tier list,
                 or null if the card isn't on that list
     image       full-resolution card art (wikia CDN)
     wikiUrl     link back to the card's file page on the wiki
     ability     { name, text }
     stats       per-rarity { odds, hp, dmg } — "—" means the wiki hasn't
                 recorded that value yet
*/
const CARDS = [
  {
    id: "green-bomber",
    name: "Green Bomber",
    altName: "Saibaman",
    role: "Attacker",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/1/16/Green-Bomber-Basic.png/revision/latest?cb=20250412113953",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Green-Bomber-Basic.png",
    ability: { name: "Acidic Attack", text: "Explodes on death, dealing this card's max health as damage." },
    stats: {
      Basic:   { odds: "1 in 2",    hp: "14",   dmg: "7" },
      Gold:    { odds: "1 in 200",  hp: "56",   dmg: "28" },
      Rainbow: { odds: "1 in 20K",  hp: "224",  dmg: "112" },
      Secret:  { odds: "1 in 2M",   hp: "896",  dmg: "448" },
    },
  },
  {
    id: "wild-hunter",
    name: "Wild Hunter",
    altName: "Gon",
    role: "Attacker",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/2/22/Wild-Hunter-Basic.png/revision/latest?cb=20250412114306",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Wild-Hunter-Basic.png",
    ability: { name: "Nen Charge", text: "Gain a charge after every attack, granting 10% more damage and health per charge (up to 3 charges)." },
    stats: {
      Basic:   { odds: "1 in 3",    hp: "16",  dmg: "8" },
      Gold:    { odds: "1 in 300",  hp: "64",  dmg: "32" },
      Rainbow: { odds: "1 in 30K",  hp: "256", dmg: "128" },
      Secret:  { odds: "1 in 3M",   hp: "1K",  dmg: "512" },
    },
  },
  {
    id: "science-king",
    name: "Science King",
    altName: "Senku Ishigami",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/4/43/Science-King-Basic.png/revision/latest?cb=20250412114742",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Science-King-Basic.png",
    ability: { name: "Genius Solution", text: "Randomly picks between gaining 15% health or 15% increased damage on entry." },
    stats: {
      Basic:   { odds: "1 in 4",    hp: "18",   dmg: "9" },
      Gold:    { odds: "1 in 400",  hp: "72",   dmg: "36" },
      Rainbow: { odds: "1 in 40K",  hp: "288",  dmg: "144" },
      Secret:  { odds: "1 in 4M",   hp: "1.1K", dmg: "576" },
    },
  },
  {
    id: "space-cowboy",
    name: "Space Cowboy",
    altName: "Spike Spiegel",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/3/3f/Space_Cow_Boy.png/revision/latest?cb=20250509012247",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Space_Cow_Boy.png",
    ability: { name: "Expert Marksman", text: "Counterattack after taking damage, firing 6 shots that each deal 5% of max health as damage." },
    stats: {
      Basic:   { odds: "1 in 8",    hp: "21",  dmg: "11" },
      Gold:    { odds: "1 in 800",  hp: "84",  dmg: "44" },
      Rainbow: { odds: "1 in 80K",  hp: "336", dmg: "176" },
      Secret:  { odds: "1 in 8M",   hp: "704", dmg: "1.3K" },
    },
  },
  {
    id: "chainsaw-fiend",
    name: "Chainsaw Fiend",
    altName: "Denji",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/2/24/Chainsaw_Feind.png/revision/latest?cb=20250509012637",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Chainsaw_Feind.png",
    ability: { name: "Chainsaw Strike", text: "25% chance to apply a bleed effect dealing 10% of the opponent's maximum health over 2 turns." },
    stats: {
      Basic:   { odds: "1 in 10",  hp: "22",  dmg: "11" },
      Gold:    { odds: "1 in 1K",  hp: "88",  dmg: "44" },
      Rainbow: { odds: "1 in 100K", hp: "352", dmg: "176" },
      Secret:  { odds: "1 in 10M", hp: "1.4K", dmg: "704" },
    },
  },
  {
    id: "cat-burglar",
    name: "Cat Burglar",
    altName: "Nami",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/1/1d/Cat_Burgler.png/revision/latest?cb=20250509013521",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Cat_Burgler.png",
    ability: { name: "Thunderbolt Tempo", text: "25% chance to summon a thunderbolt, disabling the opponent's skill for the rest of the fight." },
    stats: {
      Basic:   { odds: "1 in 25",  hp: "30",  dmg: "15" },
      Gold:    { odds: "1 in 2K",  hp: "120", dmg: "60" },
      Rainbow: { odds: "1 in 250K", hp: "480", dmg: "240" },
      Secret:  { odds: "1 in 25M", hp: "1.9K", dmg: "960" },
    },
  },
  {
    id: "crimson-eyes",
    name: "Crimson Eyes",
    altName: "Makima",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/9/9a/Crimson_eyes.png/revision/latest?cb=20250510041814",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Crimson_eyes.png",
    ability: { name: "Chain Control", text: "Stun the opponent for 1 turn on entry." },
    stats: {
      Basic:   { odds: "1 in 45",  hp: "36",  dmg: "18" },
      Gold:    { odds: "1 in 4K",  hp: "144", dmg: "72" },
      Rainbow: { odds: "1 in 450K", hp: "567", dmg: "288" },
      Secret:  { odds: "1 in 45M", hp: "2.3K", dmg: "1.1K" },
    },
  },
  {
    id: "shadow-summoner",
    name: "Shadow Summoner",
    altName: "Megumi",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/e/ee/Shadow_Summoner.png/revision/latest?cb=20250510043230",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Shadow_Summoner.png",
    ability: { name: "Cursed Beast Strike", text: "15% chance to strike with a dark aura that deals 5x damage." },
    stats: {
      Basic:   { odds: "1 in 60",  hp: "38",  dmg: "19" },
      Gold:    { odds: "1 in 6K",  hp: "152", dmg: "76" },
      Rainbow: { odds: "1 in 600K", hp: "608", dmg: "304" },
      Secret:  { odds: "1 in 60M", hp: "2.4K", dmg: "1.2K" },
    },
  },
  {
    id: "golden-king",
    name: "Golden King",
    altName: null,
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/8/89/Golden_KIng.png/revision/latest?cb=20250510044903",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Golden_KIng.png",
    ability: { name: "Gate of Wealth", text: "Disables the opponent's ability for 1 turn on entry." },
    stats: {
      Basic:   { odds: "1 in 100", hp: "44",  dmg: "22" },
      Gold:    { odds: "1 in 10K", hp: "176", dmg: "88" },
      Rainbow: { odds: "1 in 1M",  hp: "704", dmg: "352" },
      Secret:  { odds: "1 in 100M", hp: "2.8K", dmg: "1.4K" },
    },
  },
  {
    id: "knight-of-light",
    name: "Knight of Light",
    altName: null,
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/d/d3/Knight_of_Light.png/revision/latest?cb=20250510051510",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Knight_of_Light.png",
    ability: { name: "Excalibur's Radiance", text: "20% chance to blind an enemy for 1 turn, causing them to miss their attack." },
    stats: {
      Basic:   { odds: "1 in 200",  hp: "55",  dmg: "28" },
      Gold:    { odds: "1 in 20K",  hp: "220", dmg: "112" },
      Rainbow: { odds: "1 in 2M",   hp: "880", dmg: "448" },
      Secret:  { odds: "1 in 200M", hp: "3.5K", dmg: "1.7K" },
    },
  },
  {
    id: "metal-alchemist",
    name: "Metal Alchemist",
    altName: "Edward Elric",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/4/4d/Metal_Alchemist.png/revision/latest?cb=20250510055200",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Metal_Alchemist.png",
    ability: { name: "Fullmetal Transmutation", text: "30% chance to deflect an opponent's attack back at them, dealing 12% of the original damage." },
    stats: {
      Basic:   { odds: "1 in 350",  hp: "63",  dmg: "32" },
      Gold:    { odds: "1 in 35K",  hp: "252", dmg: "128" },
      Rainbow: { odds: "1 in 3.5M", hp: "1K",  dmg: "512" },
      Secret:  { odds: "1 in 350M", hp: "4K",  dmg: "2K" },
    },
  },
  {
    id: "sacred-ronin",
    name: "Sacred Ronin",
    altName: null,
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/c/ce/Sacred_Ronin.png/revision/latest?cb=20250510055056",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Sacred_Ronin.png",
    ability: { name: "Swordsman's Resolve", text: "Survive a fatal attack with 1 HP." },
    stats: {
      Basic:   { odds: "1 in 350",  hp: "63",  dmg: "32" },
      Gold:    { odds: "1 in 35K",  hp: "252", dmg: "128" },
      Rainbow: { odds: "1 in 3.5M", hp: "1K",  dmg: "512" },
      Secret:  { odds: "1 in 350M", hp: "4K",  dmg: "2K" },
    },
  },
  {
    id: "water-hashira",
    name: "Water Hashira",
    altName: "Giyuu",
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/4/49/Screenshot_%28575%29.png/revision/latest?cb=20250511015258",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Screenshot_(575).png",
    ability: { name: "Water Breathing", text: "Increases maximum health by 25% on entry." },
    stats: {
      Basic:   { odds: "1 in 400",  hp: "67",  dmg: "34" },
      Gold:    { odds: "1 in 40K",  hp: "268", dmg: "136" },
      Rainbow: { odds: "1 in 4M",   hp: "1K",  dmg: "544" },
      Secret:  { odds: "1 in 400M", hp: "4.2K", dmg: "2.1K" },
    },
  },
  {
    id: "blade-rebel",
    name: "Blade Rebel",
    altName: null,
    role: "Attacker",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/f/fd/Blade_Rebel.png/revision/latest?cb=20250511021354",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Blade_Rebel.png",
    ability: { name: "Scissor Blade Reaper", text: "Reduces the opponent's damage by 10% after every attack." },
    stats: {
      Basic:   { odds: "1 in 500",  hp: "74",  dmg: "37" },
      Gold:    { odds: "1 in 50K",  hp: "296", dmg: "148" },
      Rainbow: { odds: "1 in 5M",   hp: "1.1K", dmg: "292" },
      Secret:  { odds: "1 in 5M",   hp: "4.7K", dmg: "2.3K" },
    },
  },

  /* --- Snow Moon pool (bonus cycle, +stat multiplier over standard pool) --- */
  {
    id: "ice-dragon",
    name: "Ice Dragon",
    altName: null,
    role: "Attacker",
    pool: "Snow Moon",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/b/bb/Ice_Dragon.png/revision/latest?cb=20250801141715",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Ice_Dragon.png",
    ability: { name: "Ice Wings", text: "Applies Permafrost after landing a hit — a 50% chance each turn to freeze the opponent for 1 turn before they attack." },
    stats: {
      Basic:   { odds: "1 in 350K",  hp: "925", dmg: "463" },
      Gold:    { odds: "1 in 35M",   hp: "3.7K", dmg: "1.85K" },
      Rainbow: { odds: "1 in 3.5B",  hp: "—", dmg: "—" },
      Secret:  { odds: "1 in 350B",  hp: "—", dmg: "—" },
    },
  },
  {
    id: "snake-empress",
    name: "Snake Empress",
    altName: null,
    role: "Attacker",
    pool: "Snow Moon",
    tier: "B",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/a/a6/Snake_Empress.png/revision/latest?cb=20250801141814",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Snake_Empress.png",
    ability: { name: "Love Gaze", text: "Gains a charge every time this card is attacked. At 3 charges, heals for 40% max health and freezes the opponent for 2 turns." },
    stats: {
      Basic:   { odds: "1 in 3.5M", hp: "1.81K", dmg: "904" },
      Gold:    { odds: "1 in 350M", hp: "—", dmg: "—" },
      Rainbow: { odds: "1 in 35B",  hp: "—", dmg: "—" },
      Secret:  { odds: "1 in 3.5T", hp: "—", dmg: "—" },
    },
  },
  {
    id: "white-dragon-emperor",
    name: "White Dragon Emperor",
    altName: null,
    role: "Attacker",
    pool: "Snow Moon",
    tier: "A",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/4/4c/White_Dragon_Emperor.png/revision/latest?cb=20250801141846",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:White_Dragon_Emperor.png",
    ability: { name: "Divine Divide", text: "Reduces opponent attack by 5% every turn. If Red Dragon Emperor is in the party, this increases to 15% every turn." },
    stats: {
      Basic:   { odds: "1 in 5M",   hp: "2.06K", dmg: "1.03K" },
      Gold:    { odds: "1 in 500M", hp: "—", dmg: "—" },
      Rainbow: { odds: "1 in 50B",  hp: "—", dmg: "—" },
      Secret:  { odds: "1 in 5T",   hp: "—", dmg: "—" },
    },
  },

  /* --- Support Cards --- */
  {
    id: "substitution-log",
    name: "Substitution Log",
    altName: null,
    role: "Support",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/4/4d/Screenshot_%28550%29.png/revision/latest?cb=20250509004143",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Screenshot_(550).png",
    ability: { name: "Substitution", text: "10% chance to dodge an attack." },
    stats: { Base: { odds: "1 in 1K", hp: "—", dmg: "—" } },
  },
  {
    id: "ninja-vest",
    name: "Ninja Vest",
    altName: null,
    role: "Support",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/9/9b/Ninja_vest.png/revision/latest?cb=20250509010157",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Ninja_vest.png",
    ability: { name: "Demon's Blessing", text: "Boosts health by 10%." },
    stats: { Base: { odds: "1 in 2K", hp: "—", dmg: "—" } },
  },
  {
    id: "sealed-cube",
    name: "Sealed Cube",
    altName: null,
    role: "Support",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/4/4c/Sealed_Cube.png/revision/latest?cb=20250509010520",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Sealed_Cube.png",
    ability: { name: "Eternal Imprisonment", text: "The first attack by an opponent instead imprisons them for 1 turn." },
    stats: { Base: { odds: "1 in 5K", hp: "—", dmg: "—" } },
  },
  {
    id: "cursed-ledger",
    name: "Cursed Ledger",
    altName: null,
    role: "Support",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/5/5d/Cursed_Ledger.png/revision/latest?cb=20250509010742",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Cursed_Ledger.png",
    ability: { name: "Life Siphon", text: "Reduces the health of the entire enemy party by 2.5% every other attack." },
    stats: { Base: { odds: "1 in 10K", hp: "—", dmg: "—" } },
  },
  {
    id: "mystical-spheres",
    name: "Mystical Spheres",
    altName: null,
    role: "Support",
    pool: "Standard Pool",
    tier: null,
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/0/0d/Mystical_Spheres.png/revision/latest?cb=20250509011038",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Mystical_Spheres.png",
    ability: { name: "Wish Fulfillment", text: "Randomly grants 20% bonus health, 20% bonus attack, or 20% dodge chance on entry." },
    stats: { Base: { odds: "1 in 25K", hp: "—", dmg: "—" } },
  },
  {
    id: "beast-contract",
    name: "Beast Contract",
    altName: null,
    role: "Support",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/7/7d/Beast_Contract.png/revision/latest?cb=20250509011301",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Beast_Contract.png",
    ability: { name: "Beast Summoner", text: "30% chance for the beast to counterattack, dealing 20% of the opponent's max health." },
    stats: { Base: { odds: "1 in 50K", hp: "—", dmg: "—" } },
  },
  {
    id: "dragon-sin-blades",
    name: "Dragon Sin Blades",
    altName: null,
    role: "Support",
    pool: "Standard Pool",
    tier: "C",
    image: "https://static.wikia.nocookie.net/anime-card-clash/images/6/62/Dragon_Sin_Blades.png/revision/latest?cb=20250509011625",
    wikiUrl: "https://anime-card-clash.fandom.com/wiki/File:Dragon_Sin_Blades.png",
    ability: { name: "Double Strike", text: "Ability text is unfinished on the source wiki page — check the wiki link for updates." },
    stats: { Base: { odds: "1 in 100K", hp: "—", dmg: "—" } },
  },
];
